### PR TITLE
Pass a message object to js.SDK driver, not a string

### PR DESCRIPTION
**Pull request by ear-dev**
This results in the attachments object getting passed through the connector to the clients.

### CODE REVIEW

**Comment by timkinnane** [comment]
@ear-dev does this work in current state? Looking at the methods in the SDK, I think `sendDirectToUser` and `sendToRoomId` only accept a string or array of strings.

Those methods are basic helpers to provide a shorthand to constructing the message object, adding text and sending all-in-one.

If you want to create and return a custom message object to add further attributes, you can use `driver.prepareMessage` then `driver.sendMessage` OR if you just pass an object with all the required attributes to `driver.sendMessage` it send as is.

See here:
https://github.com/RocketChat/Rocket.Chat.js.SDK/blob/be6855e333907cef7a6a8154f189bba38da9ca84/src/lib/driver.ts#L526-L542

And here for the accepted message attributes (based on the schema within Rocket.Chat):
https://github.com/RocketChat/Rocket.Chat.js.SDK/blob/master/src/config/messageInterfaces.ts

For the `RocketChatBot.js` example, that would require changing the `rid` on the created message depending on that messageSource conditional, something like:

```js
            var newMessage = driver.prepareMessage({
                msg: message.text,
                attachments: message.attachments || []
            })
            
            if (bot.connected) {
                if (messageSource === 'directMessage') {
                    newMessage.rid = await driver.getDirectMessageRoomId(userName);
                } else if (messageSource === 'liveChat') {
                    // TODO: implement answer to livechat
                } else if (messageSource === 'privateChannel') {
                    newMessage.rid = roomID;
                } else if (messageSource === 'channel') {
                    newMessage.rid = roomID;
                }
                await driver.sendMessage(newMessage);
            }
```

**Comment by timkinnane** [comment]
Maybe a cleaner way of doing that would be:

```js
if (bot.connected) {
  var newMessage = {
    rid: roomID,
    msg: message.text,
    attachments: message.attachments || []
  }
  if (messageSource === 'directMessage') {
    newMessage.rid = await driver.getDirectMessageRoomId(userName)
  }
  await driver.sendMessage(newMessage)
}
```

**Comment by ear-dev** [comment]
@timkinnane The way I originally wrote it does actually work, but I only tested for the messageSource == channel case.  I think the others will also work, but I will confirm.  

The reason it works is because prepareMessage() in the SDK takes either a string or an IMessage.  Doesn't that look right to you?

Perhaps you did not intend for it to work that way, but I believe it works very elegantly. 

What you have suggested is certainly more explicit, and also a nice example for how to use the SDK.   I suppose it's a matter of best practices for deciding which style we choose?

**Comment by timkinnane** [comment]
@ear-dev You're right! I was just going by the type definitions, which need updating to reflect the real options. Have made an issue for that and will get round to it, but it works now in JS because it's not enforcing the strict types.

https://github.com/RocketChat/Rocket.Chat.js.SDK/issues/18

**Comment by Sing-Li** [comment]
Let's merge this for now so we get the attachment capabilities, and then adapt the code if the type checking is tightened in the future.

**Pull request merged**
